name: Verify
description: Run tests and lint

runs:
  using: "composite"
  steps:
    - name: Lint code
      run: npm run lint
      shell: bash

    - name: Run type checking
      run: npm run typecheck
      shell: bash

    - name: Check build
      run: npm run build
      shell: bash
      env:
        # Skip telemetry during CI builds
        NEXT_TELEMETRY_DISABLED: 1
        DATABASE_URL: postgresql://user:pass@localhost:5432/test
        BETTER_AUTH_SECRET: test-secret-for-build
        NEXT_PUBLIC_BETTER_AUTH_URL: http://localhost:3000
        GOOGLE_CLIENT_ID: test-client-id
        GOOGLE_CLIENT_SECRET: test-client-secret
        EMAIL_SERVER_HOST: smtp.test.com
        EMAIL_SERVER_PORT: "587"
        EMAIL_SERVER_USER: test@test.com
        EMAIL_SERVER_PASSWORD: test-password
        EMAIL_FROM: test@test.com
        EMAIL_SERVICE: gmail
        STRIPE_SECRET_KEY: sk_test_fake
        STRIPE_WEBHOOK_SECRET: whsec_fake
        STRIPE_API_VER: "2024-06-20"
        SENTRY_AUTH_TOKEN: fake-token
        NEXT_PUBLIC_SENTRY_DSN: https://fake@sentry.io/123
        NEXT_PUBLIC_SENTRY_ORG: test-org
        NEXT_PUBLIC_SENTRY_PROJECT: test-project
        NEXT_PUBLIC_APP_NAME: Test App
        NEXT_PUBLIC_COMPANY_NAME: Test Company
