name: Verify
description: Run tests and lint

runs:
  using: "composite"
  steps:
    - name: Lint code
      run: npm run lint
      shell: bash

    - name: Run type checking
      run: npm run typecheck
      shell: bash
      env:
        SKIP_ENV_CHECK: "true"

    - name: Check build
      run: npm run build
      shell: bash
      env:
        # Skip telemetry during CI builds
        NEXT_TELEMETRY_DISABLED: 1
        SKIP_ENV_CHECK: "true"
