name: Pull Request

on:
  pull_request:
    branches: [main]

jobs:
  pr-check:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - if: ${{ github.actor == 'dependabot[bot]' }}
        name: Fetch Git History
        run: git fetch --prune --unshallow

      - name: Setup Project
        uses: ./.github/actions/setup-project

      - if: ${{ github.actor != 'dependabot[bot]' }}
        name: Check Outdated Dependencies
        uses: ./.github/actions/deps-outdated

      - name: Check Critical Dependencies
        uses: ./.github/actions/deps-audit

      - name: Verify Project
        uses: ./.github/actions/verify-project

      - if: ${{ github.actor == 'dependabot[bot]' && success() }}
        name: Auto-approve minor/patch dependency updates
        uses: hmarr/auto-approve-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
